### ISSUE TITLE
🐛 동일한 PV 클레임에서 복수개의 볼륨을 생성하여 마운트할 시 문제 발생

### ISSUE THREAD

**Issue by Yanghyeondong** [Yanghyeondong/DEV-ROOM#18]
###  문제가 발생한 기능
- PV에서 교육자용 public 폴더는 readonly로, 학생용 private 폴더는 readwrite 권한으로 학생 컨테이너 마운트 

### 발생한 문제점 및 버그
- 동일한 Claim에 대해 여러개의 볼륨을 정의하고 마운트 할시, ContinerCreating 단계에서 무한 대기에 진입  
kubectl describe로도 정확한 정보는 알 수 없기 때문에 자세한 이유는 모르지만, 해당 부분이 문제라는 것은 확인

#### 문제 코드

```yaml
    volumes:
      - name: config
        configMap:
          name: student-{{ $student.id }}-{{ $class.name | lower }}-config
      - name: data1
        persistentVolumeClaim:
          claimName: {{ $.Values.pv_name }}-claim
      - name: data2
        persistentVolumeClaim:
          claimName: {{ $.Values.pv_name }}-claim
```

### 해결 방안
PV와 PV-Claim을 2개로 분리했습니다. Helm 배포시에는 반복문을 사용하여 yaml을 작성하도록 하였습니다.
이때, PV도 분리한 이유는 PV와 PV-Claim 이 서로 1:1 대응이기 때문입니다.
